import type { PersonnelCard, EventCard } from '../types/card'

// ── 人員カード ────────────────────────────────────────────────
export const PERSONNEL_CARDS: PersonnelCard[] = [
  {
    id: 'p_tanaka', type: 'personnel', rarity: 'common',
    personnelType: 'engineer', name: '田中エンジニア',
    title: 'バックエンドエンジニア', skills: ['backend'],
    productivity: 20, bugRate: 0.05, costPerTurn: 80,
    flavor: '寡黙だが仕事は速い。レビューは苦手。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_sato', type: 'personnel', rarity: 'common',
    personnelType: 'engineer', name: '佐藤エンジニア',
    title: 'フロントエンドエンジニア', skills: ['frontend'],
    productivity: 18, bugRate: 0.06, costPerTurn: 75,
    flavor: 'デザインへのこだわりが強すぎる。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_yamada', type: 'personnel', rarity: 'common',
    personnelType: 'newcomer', name: '山田新人',
    title: '新卒エンジニア', skills: ['general'],
    productivity: 8, bugRate: 0.25, costPerTurn: 30,
    flavor: '積極的だが経験が足りない。育てれば伸びる。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_suzuki', type: 'personnel', rarity: 'common',
    personnelType: 'newcomer', name: '鈴木新人',
    title: '第二新卒エンジニア', skills: ['general'],
    productivity: 6, bugRate: 0.30, costPerTurn: 28,
    flavor: '前職は飲食業。でも熱意はある。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_kimura', type: 'personnel', rarity: 'uncommon',
    personnelType: 'lead', name: '木村リーダー',
    title: 'テックリード', skills: ['backend', 'frontend'],
    productivity: 15, bugRate: 0.04, costPerTurn: 100,
    flavor: 'マネジメントもできる稀有な存在。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_matsumoto', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '松本インフラ担当',
    title: 'インフラエンジニア', skills: ['infra'],
    productivity: 20, bugRate: 0.04, costPerTurn: 90,
    flavor: 'インフラ以外には興味がない。本当に。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_takahashi', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '高橋QA担当',
    title: 'QAエンジニア', skills: ['qa'],
    productivity: 12, bugRate: 0.01, costPerTurn: 70,
    flavor: 'バグを見つけるのが生きがい。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_fl_fujiwara', type: 'personnel', rarity: 'rare',
    personnelType: 'freelance', name: '藤原フリーランス',
    title: 'フルスタックエンジニア', skills: ['backend', 'frontend', 'infra'],
    productivity: 28, bugRate: 0.03, costPerTurn: 150,
    flavor: '高いが確実。でも3ターンで去る。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_ito', type: 'personnel', rarity: 'common',
    personnelType: 'engineer', name: '伊藤デザイナー',
    title: 'UIデザイナー', skills: ['design', 'frontend'],
    productivity: 14, bugRate: 0.05, costPerTurn: 65,
    flavor: 'ピクセルパーフェクトにこだわる職人。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_nakamura', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '中村フルスタック',
    title: 'フルスタックエンジニア', skills: ['frontend', 'backend'],
    productivity: 16, bugRate: 0.08, costPerTurn: 110,
    flavor: '器用貧乏と言われるが本人は気にしていない。',
    turnsOnTask: 0, condition: 100,
  },
  {
    id: 'p_god_engineer', type: 'personnel', rarity: 'legendary',
    personnelType: 'freelance', name: '伝説のエンジニア・坂本',
    title: '神エンジニア', skills: ['backend', 'frontend', 'infra', 'qa'],
    productivity: 40, bugRate: 0.01, costPerTurn: 250,
    flavor: 'GitHubのスター数が笑えない数字。来てくれるだけで奇跡。',
    turnsOnTask: 0, condition: 100,
  },
]

// ── イベントカード ──────────────────────────────────────────
export const EVENT_CARDS: EventCard[] = [
  {
    id: 'e_spec_change_minor',
    type: 'event',
    name: '軽微な仕様変更',
    description: 'クライアントから「ちょっとだけ変えてほしい」という連絡が入った。',
    severity: 'negative',
    flavor: '「ちょっとだけ」は信用できない。',
    choices: [
      {
        id: 'accept',
        label: '受け入れる',
        description: 'クライアントの要望に応える。進捗が少し戻る。',
        effects: [{ type: 'progress_delta', value: -20 }],
      },
      {
        id: 'negotiate',
        label: '交渉する',
        description: 'スコープを絞って影響を最小化。品質が少し下がる。',
        effects: [{ type: 'quality_delta', value: -5 }],
      },
    ],
  },
  {
    id: 'e_spec_change_major',
    type: 'event',
    name: '大型仕様変更',
    description: '「やっぱりコンセプトから変えたい」。取り組み中のフェーズが振り出しに戻る。',
    severity: 'critical',
    flavor: 'これが現実のプロジェクトというものだ。',
    choices: [
      {
        id: 'accept',
        label: '全て受け入れる',
        description: '現フェーズの進捗をリセット。クライアント満足度は上がる。',
        effects: [{ type: 'progress_reset' }, { type: 'quality_delta', value: 5 }],
      },
      {
        id: 'partial',
        label: '一部のみ対応',
        description: '品質が下がるが影響を限定できる。',
        effects: [{ type: 'progress_delta', value: -40 }, { type: 'quality_delta', value: -10 }],
      },
    ],
  },
  {
    id: 'e_key_person_quit',
    type: 'event',
    name: 'キーパーソン退職',
    description: '「一身上の都合で…」。重要なメンバーが突然いなくなった。',
    severity: 'critical',
    flavor: '引き継ぎ？そんなものはなかった。',
    choices: [
      {
        id: 'accept',
        label: '受け入れる',
        description: '担当タスクが停止。残りメンバーで対処する。',
        effects: [{ type: 'remove_personnel' }],
      },
      {
        id: 'retain',
        label: '引き留める（コスト増）',
        description: '追加予算で説得。コストが増加。',
        effects: [{ type: 'cost_delta', value: 200 }],
      },
    ],
  },
  {
    id: 'e_tech_debt',
    type: 'event',
    name: '技術的負債爆発',
    description: '後回しにしてきたツケが回ってきた。コードが動かなくなっている。',
    severity: 'critical',
    flavor: '「あとでやる」はやらないと同義だ。',
    choices: [
      {
        id: 'fix_now',
        label: '今すぐ対処',
        description: 'このターンの進捗がゼロになるが、状態異常を解除。',
        effects: [{ type: 'progress_delta', value: -30 }, { type: 'remove_status', statusType: 'debt' }],
      },
      {
        id: 'ignore',
        label: '後回し',
        description: '技術的負債の状態異常が付与される。',
        effects: [{ type: 'add_status', statusType: 'debt' }],
      },
    ],
  },
  {
    id: 'e_fire',
    type: 'event',
    name: '炎上発生',
    description: 'バグ報告が殺到している。プロジェクトが炎上状態に突入。',
    severity: 'critical',
    flavor: '🔥 誰も望んでいなかった。でも誰も止められなかった。',
    choices: [
      {
        id: 'all_hands',
        label: '全員で対処',
        description: '炎上を解除。ただしこのターンの通常進捗はゼロ。',
        effects: [{ type: 'remove_status', statusType: 'fire' }, { type: 'quality_delta', value: 5 }],
      },
      {
        id: 'continue',
        label: '開発継続しながら対処',
        description: '品質が下がるが進捗は続く。炎上は続く。',
        effects: [{ type: 'quality_delta', value: -15 }, { type: 'add_status', statusType: 'fire' }],
      },
    ],
  },
  {
    id: 'e_flu',
    type: 'event',
    name: 'メンバー体調不良',
    description: '「熱が出て…」。一人のメンバーが今週欠勤する。',
    severity: 'negative',
    flavor: 'インフルエンザの季節。あなたは大丈夫？',
    choices: [
      {
        id: 'rest',
        label: '休ませる',
        description: '1ターン離脱。次のターンからコンディション回復。',
        effects: [{ type: 'progress_delta', value: -10 }],
      },
    ],
  },
  {
    id: 'e_review',
    type: 'event',
    name: 'コードレビュー発見',
    description: 'レビュー中に重大なバグが見つかった。早期発見で被害が最小限。',
    severity: 'positive',
    flavor: 'レビューをちゃんとやっていたおかげだ。',
    choices: [
      {
        id: 'fix',
        label: 'すぐ修正',
        description: 'バグ修正。品質が上昇。',
        effects: [{ type: 'quality_delta', value: 10 }, { type: 'remove_bug', value: 2 }],
      },
    ],
  },
  {
    id: 'e_god_engineer',
    type: 'event',
    name: '神エンジニア参戦',
    description: '「空いてたので手伝いますよ」。伝説のエンジニアがチームに加わる。',
    severity: 'positive',
    flavor: 'GitHubスター数が桁違いの人物が現れた。',
    choices: [
      {
        id: 'recruit',
        label: '採用する',
        description: '高コストだが強力な戦力が加わる。',
        effects: [{ type: 'quality_delta', value: 15 }],
      },
    ],
  },
  {
    id: 'e_client_happy',
    type: 'event',
    name: 'クライアント絶賛',
    description: '「こんなに良いとは思わなかった」。クオリティが評価された。',
    severity: 'positive',
    flavor: '報われることもある。',
    choices: [
      {
        id: 'good',
        label: 'ありがとうございます',
        description: '品質スコアとデリバリー評価が上昇。',
        effects: [{ type: 'quality_delta', value: 8 }, { type: 'delivery_delta', value: 5 }],
      },
    ],
  },
  {
    id: 'e_meeting_hell',
    type: 'event',
    name: '会議地獄',
    description: '今週は会議が多すぎて開発時間が取れない。',
    severity: 'negative',
    flavor: '会議のための会議。これが社会だ。',
    choices: [
      {
        id: 'attend_all',
        label: '全て出席',
        description: '今週の全進捗が50%に減少。',
        effects: [{ type: 'progress_delta', value: -15 }],
      },
      {
        id: 'skip_some',
        label: '一部欠席',
        description: 'コスト増だが進捗への影響が少ない。',
        effects: [{ type: 'cost_delta', value: 30 }, { type: 'progress_delta', value: -5 }],
      },
    ],
  },
  {
    id: 'e_overtime',
    type: 'event',
    name: '残業スパート',
    description: 'チームが自発的に残業を申し出た。進捗は上がるがコンディションに影響。',
    severity: 'neutral',
    flavor: '「頑張ります」の後が心配だ。',
    choices: [
      {
        id: 'allow',
        label: '認める',
        description: '今週の進捗+30%。次のターンのコンディションが下がる。',
        effects: [{ type: 'progress_delta', value: 20 }, { type: 'cost_delta', value: 50 }],
      },
      {
        id: 'deny',
        label: '帰らせる',
        description: '進捗への変化なし。チームのコンディション維持。',
        effects: [],
      },
    ],
  },
  {
    id: 'e_new_tool',
    type: 'event',
    name: '新ツール導入提案',
    description: '「このツール使えば生産性が上がります」。エンジニアが新ツールを提案。',
    severity: 'neutral',
    flavor: 'バズワードが含まれていたら要注意。',
    choices: [
      {
        id: 'adopt',
        label: '導入する',
        description: '学習コスト1ターン。その後は生産性+10%。',
        effects: [{ type: 'progress_delta', value: -15 }, { type: 'quality_delta', value: 5 }],
      },
      {
        id: 'reject',
        label: '見送る',
        description: '変化なし。',
        effects: [],
      },
    ],
  },
]
