import type { PersonnelCard, EventCard } from '../types/card'

// ── 人員カード ────────────────────────────────────────────────
export const PERSONNEL_CARDS: PersonnelCard[] = [
  {
    id: 'p_tanaka', type: 'personnel', rarity: 'common',
    personnelType: 'engineer', name: '田中エンジニア',
    title: 'バックエンドエンジニア', skills: ['backend'],
    color: 'tech',
    productivity: 20, actualOutputRange: [17, 23], bugRate: 0.05, costPerTurn: 80,
    flavor: '寡黙だが仕事は速い。レビューは苦手。',
    personalEvents: ['e_tech_debt', 'e_overtime'],
    engineeringSkill: 65, engineeringSkillRange: [55, 75],
    managementSkill: 25, managementSkillRange: [15, 35],
    communicationSkill: 30, communicationSkillRange: [20, 40],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_sato', type: 'personnel', rarity: 'common',
    personnelType: 'engineer', name: '佐藤エンジニア',
    title: 'フロントエンドエンジニア', skills: ['frontend'],
    color: 'drive',
    productivity: 18, actualOutputRange: [15, 22], bugRate: 0.06, costPerTurn: 75,
    flavor: 'デザインへのこだわりが強すぎる。',
    personalEvents: ['e_spec_change_minor', 'e_new_tool'],
    engineeringSkill: 55, engineeringSkillRange: [45, 65],
    managementSkill: 30, managementSkillRange: [20, 40],
    communicationSkill: 45, communicationSkillRange: [35, 55],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_yamada', type: 'personnel', rarity: 'common',
    personnelType: 'newcomer', name: '山田新人',
    title: '新卒エンジニア', skills: ['general'],
    color: 'adjust',
    productivity: 8, actualOutputRange: [5, 13], bugRate: 0.25, costPerTurn: 30,
    flavor: '積極的だが経験が足りない。育てれば伸びる。',
    personalEvents: ['e_flu', 'e_new_tool'],
    engineeringSkill: 25, engineeringSkillRange: [15, 35],
    managementSkill: 18, managementSkillRange: [10, 25],
    communicationSkill: 53, communicationSkillRange: [40, 65],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_suzuki', type: 'personnel', rarity: 'common',
    personnelType: 'newcomer', name: '鈴木新人',
    title: '第二新卒エンジニア', skills: ['general'],
    color: 'adjust',
    productivity: 6, actualOutputRange: [4, 10], bugRate: 0.30, costPerTurn: 28,
    flavor: '前職は飲食業。でも熱意はある。',
    personalEvents: ['e_flu', 'e_meeting_hell'],
    engineeringSkill: 18, engineeringSkillRange: [10, 25],
    managementSkill: 13, managementSkillRange: [5, 20],
    communicationSkill: 40, communicationSkillRange: [30, 50],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_kimura', type: 'personnel', rarity: 'uncommon',
    personnelType: 'lead', name: '木村リーダー',
    title: 'テックリード', skills: ['backend', 'frontend'],
    color: 'adjust',
    productivity: 15, actualOutputRange: [13, 18], bugRate: 0.04, costPerTurn: 100,
    flavor: 'マネジメントもできる稀有な存在。',
    personalEvents: ['e_code_review_find', 'e_overtime'],
    engineeringSkill: 50, engineeringSkillRange: [40, 60],
    managementSkill: 70, managementSkillRange: [60, 80],
    communicationSkill: 70, communicationSkillRange: [60, 80],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_matsumoto', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '松本インフラ担当',
    title: 'インフラエンジニア', skills: ['infra'],
    color: 'tech',
    productivity: 20, actualOutputRange: [17, 24], bugRate: 0.04, costPerTurn: 90,
    flavor: 'インフラ以外には興味がない。本当に。',
    personalEvents: ['e_new_tool', 'e_tech_debt'],
    engineeringSkill: 70, engineeringSkillRange: [60, 80],
    managementSkill: 20, managementSkillRange: [10, 30],
    communicationSkill: 25, communicationSkillRange: [15, 35],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_takahashi', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '高橋QA担当',
    title: 'QAエンジニア', skills: ['qa'],
    color: 'drive',
    productivity: 12, actualOutputRange: [10, 15], bugRate: 0.01, costPerTurn: 70,
    flavor: 'バグを見つけるのが生きがい。',
    personalEvents: ['e_code_review_find', 'e_client_happy'],
    engineeringSkill: 55, engineeringSkillRange: [45, 65],
    managementSkill: 45, managementSkillRange: [35, 55],
    communicationSkill: 65, communicationSkillRange: [55, 75],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_fl_fujiwara', type: 'personnel', rarity: 'rare',
    personnelType: 'specialist', name: '藤原スペシャリスト',
    title: 'フルスタックスペシャリスト', skills: ['backend', 'frontend', 'infra'],
    color: 'blitz',
    productivity: 28, actualOutputRange: [24, 34], bugRate: 0.03, costPerTurn: 150,
    flavor: '高いが確実。専門知識は本物。',
    personalEvents: ['e_overtime', 'e_spec_change_minor'],
    engineeringSkill: 80, engineeringSkillRange: [70, 90],
    managementSkill: 50, managementSkillRange: [40, 60],
    communicationSkill: 55, communicationSkillRange: [45, 65],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_ito', type: 'personnel', rarity: 'common',
    personnelType: 'engineer', name: '伊藤デザイナー',
    title: 'UIデザイナー', skills: ['design', 'frontend'],
    color: 'drive',
    productivity: 14, actualOutputRange: [11, 18], bugRate: 0.05, costPerTurn: 65,
    flavor: 'ピクセルパーフェクトにこだわる職人。',
    personalEvents: ['e_spec_change_minor', 'e_client_happy'],
    engineeringSkill: 50, engineeringSkillRange: [40, 60],
    managementSkill: 30, managementSkillRange: [20, 40],
    communicationSkill: 60, communicationSkillRange: [50, 70],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_nakamura', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '中村フルスタック',
    title: 'フルスタックエンジニア', skills: ['frontend', 'backend'],
    color: 'drive',
    productivity: 16, actualOutputRange: [13, 20], bugRate: 0.08, costPerTurn: 110,
    flavor: '器用貧乏と言われるが本人は気にしていない。',
    personalEvents: ['e_flu', 'e_tech_debt'],
    engineeringSkill: 50, engineeringSkillRange: [40, 60],
    managementSkill: 35, managementSkillRange: [25, 45],
    communicationSkill: 45, communicationSkillRange: [35, 55],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_god_engineer', type: 'personnel', rarity: 'legendary',
    personnelType: 'specialist', name: '伝説のエンジニア・坂本',
    title: '神エンジニア', skills: ['backend', 'frontend', 'infra', 'qa'],
    color: 'blitz',
    productivity: 40, actualOutputRange: [36, 46], bugRate: 0.01, costPerTurn: 250,
    flavor: 'GitHubのスター数が笑えない数字。来てくれるだけで奇跡。',
    personalEvents: ['e_code_review_find', 'e_client_happy', 'e_god_engineer'],
    engineeringSkill: 93, engineeringSkillRange: [85, 100],
    managementSkill: 75, managementSkillRange: [65, 85],
    communicationSkill: 75, communicationSkillRange: [65, 85],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  // ── 追加エンジニア（大規模チーム向け） ──────────────────────
  {
    id: 'p_ohno', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '大野データエンジニア',
    title: 'データエンジニア', skills: ['backend', 'infra'],
    color: 'tech',
    productivity: 22, actualOutputRange: [19, 26], bugRate: 0.04, costPerTurn: 95,
    flavor: 'データパイプラインを愛している。',
    personalEvents: ['e_tech_debt', 'e_new_tool'],
    engineeringSkill: 65, engineeringSkillRange: [55, 75],
    managementSkill: 40, managementSkillRange: [30, 50],
    communicationSkill: 45, communicationSkillRange: [35, 55],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_nishimura', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '西村セキュリティ担当',
    title: 'セキュリティエンジニア', skills: ['infra', 'qa'],
    color: 'tech',
    productivity: 18, actualOutputRange: [15, 22], bugRate: 0.02, costPerTurn: 105,
    flavor: '脆弱性を見つけることで眠れる夜がある。',
    personalEvents: ['e_code_review_find', 'e_meeting_hell'],
    engineeringSkill: 70, engineeringSkillRange: [60, 80],
    managementSkill: 45, managementSkillRange: [35, 55],
    communicationSkill: 50, communicationSkillRange: [40, 60],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_kobayashi', type: 'personnel', rarity: 'uncommon',
    personnelType: 'lead', name: '小林スクラムマスター',
    title: 'スクラムマスター', skills: ['general'],
    color: 'adjust',
    productivity: 12, actualOutputRange: [10, 15], bugRate: 0.03, costPerTurn: 120,
    flavor: 'チームの潤滑油。本人の生産性より他者の生産性を上げる。',
    personalEvents: ['e_overtime', 'e_client_happy'],
    engineeringSkill: 40, engineeringSkillRange: [30, 50],
    managementSkill: 80, managementSkillRange: [70, 90],
    communicationSkill: 80, communicationSkillRange: [70, 90],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_hashimoto', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '橋本シニアデザイナー',
    title: 'シニアUIデザイナー', skills: ['design', 'frontend'],
    color: 'drive',
    productivity: 16, actualOutputRange: [13, 20], bugRate: 0.04, costPerTurn: 115,
    flavor: 'UXは哲学だと信じている。',
    personalEvents: ['e_spec_change_minor', 'e_client_happy'],
    engineeringSkill: 55, engineeringSkillRange: [45, 65],
    managementSkill: 45, managementSkillRange: [35, 55],
    communicationSkill: 65, communicationSkillRange: [55, 75],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
  {
    id: 'p_watanabe', type: 'personnel', rarity: 'uncommon',
    personnelType: 'engineer', name: '渡辺モバイルエンジニア',
    title: 'モバイルエンジニア', skills: ['frontend'],
    color: 'drive',
    productivity: 20, actualOutputRange: [17, 24], bugRate: 0.06, costPerTurn: 100,
    flavor: 'iOS/Android両方できる。本人は当然だと思っている。',
    personalEvents: ['e_new_tool', 'e_flu'],
    engineeringSkill: 65, engineeringSkillRange: [55, 75],
    managementSkill: 30, managementSkillRange: [20, 40],
    communicationSkill: 50, communicationSkillRange: [40, 60],
    turnsOnTask: 0, condition: 100, analysisCount: 0,
  },
]

// ── イベントカード ──────────────────────────────────────────
export const EVENT_CARDS: EventCard[] = [
  {
    id: 'e_spec_change_minor',
    type: 'event',
    name: '軽微な仕様変更',
    description: 'クライアントから「ちょっとだけ変えてほしい」という連絡が入った。',
    severity: 'negative',
    flavor: '「ちょっとだけ」は信用できない。',
    choices: [
      {
        id: 'accept',
        label: '受け入れる',
        description: 'クライアントの要望に応える。進捗が少し戻る。',
        effects: [{ type: 'progress_delta', value: -20 }],
      },
      {
        id: 'negotiate',
        label: '交渉する',
        description: 'スコープを絞って影響を最小化。品質が少し下がる。',
        effects: [{ type: 'quality_delta', value: -5 }],
      },
    ],
  },
  {
    id: 'e_spec_change_major',
    type: 'event',
    name: '大型仕様変更',
    description: '「やっぱりコンセプトから変えたい」。取り組み中のフェーズが振り出しに戻る。',
    severity: 'critical',
    flavor: 'これが現実のプロジェクトというものだ。',
    choices: [
      {
        id: 'accept',
        label: '全て受け入れる',
        description: '現フェーズの進捗をリセット。クライアント満足度は上がる。',
        effects: [{ type: 'progress_reset' }, { type: 'quality_delta', value: 5 }],
      },
      {
        id: 'partial',
        label: '一部のみ対応',
        description: '品質が下がるが影響を限定できる。',
        effects: [{ type: 'progress_delta', value: -40 }, { type: 'quality_delta', value: -10 }],
      },
    ],
  },
  {
    id: 'e_key_person_quit',
    type: 'event',
    name: 'キーパーソン退職',
    description: '「一身上の都合で…」。重要なメンバーが突然いなくなった。',
    severity: 'critical',
    flavor: '引き継ぎ？そんなものはなかった。',
    choices: [
      {
        id: 'accept',
        label: '受け入れる',
        description: '担当タスクが停止。残りメンバーで対処する。',
        effects: [{ type: 'remove_personnel' }],
      },
      {
        id: 'retain',
        label: '引き留める（コスト増）',
        description: '追加予算で説得。コストが増加。',
        effects: [{ type: 'cost_delta', value: 200 }],
      },
    ],
  },
  {
    id: 'e_tech_debt',
    type: 'event',
    name: '技術的負債爆発',
    description: '後回しにしてきたツケが回ってきた。コードが動かなくなっている。',
    severity: 'critical',
    flavor: '「あとでやる」はやらないと同義だ。',
    choices: [
      {
        id: 'fix_now',
        label: '今すぐ対処',
        description: 'このターンの進捗がゼロになるが、状態異常を解除。',
        effects: [{ type: 'progress_delta', value: -30 }, { type: 'remove_status', statusType: 'debt' }],
      },
      {
        id: 'ignore',
        label: '後回し',
        description: '技術的負債の状態異常が付与される。',
        effects: [{ type: 'add_status', statusType: 'debt' }],
      },
    ],
  },
  {
    id: 'e_fire',
    type: 'event',
    name: '炎上発生',
    description: 'バグ報告が殺到している。プロジェクトが炎上状態に突入。',
    severity: 'critical',
    flavor: '誰も望んでいなかった。でも誰も止められなかった。',
    choices: [
      {
        id: 'all_hands',
        label: '全員で対処',
        description: '炎上を解除。ただしこのターンの通常進捗はゼロ。',
        effects: [{ type: 'remove_status', statusType: 'fire' }, { type: 'quality_delta', value: 5 }],
      },
      {
        id: 'continue',
        label: '開発継続しながら対処',
        description: '品質が下がるが進捗は続く。炎上は続く。',
        effects: [{ type: 'quality_delta', value: -15 }, { type: 'add_status', statusType: 'fire' }],
      },
    ],
  },
  {
    id: 'e_flu',
    type: 'event',
    name: 'メンバー体調不良',
    description: '「熱が出て…」。一人のメンバーが今週欠勤する。',
    severity: 'negative',
    flavor: 'インフルエンザの季節。あなたは大丈夫？',
    choices: [
      {
        id: 'rest',
        label: '休ませる',
        description: '1ターン離脱。次のターンからコンディション回復。',
        effects: [{ type: 'progress_delta', value: -10 }],
      },
    ],
  },
  {
    id: 'e_code_review_find',
    type: 'event',
    name: 'コードレビュー発見',
    description: 'レビュー中に重大なバグが見つかった。早期発見で被害が最小限。',
    severity: 'positive',
    flavor: 'レビューをちゃんとやっていたおかげだ。',
    choices: [
      {
        id: 'fix',
        label: 'すぐ修正',
        description: 'バグ修正。品質が上昇。',
        effects: [{ type: 'quality_delta', value: 10 }, { type: 'remove_bug', value: 2 }],
      },
    ],
  },
  {
    id: 'e_god_engineer',
    type: 'event',
    name: '神エンジニア参戦',
    description: '「空いてたので手伝いますよ」。伝説のエンジニアがチームに加わる。',
    severity: 'positive',
    flavor: 'GitHubスター数が桁違いの人物が現れた。',
    choices: [
      {
        id: 'recruit',
        label: '採用する',
        description: '高コストだが強力な戦力が加わる。',
        effects: [{ type: 'quality_delta', value: 15 }],
      },
    ],
  },
  {
    id: 'e_client_happy',
    type: 'event',
    name: 'クライアント絶賛',
    description: '「こんなに良いとは思わなかった」。クオリティが評価された。',
    severity: 'positive',
    flavor: '報われることもある。',
    choices: [
      {
        id: 'good',
        label: 'ありがとうございます',
        description: '品質スコアとデリバリー評価が上昇。',
        effects: [{ type: 'quality_delta', value: 8 }, { type: 'delivery_delta', value: 5 }],
      },
    ],
  },
  {
    id: 'e_meeting_hell',
    type: 'event',
    name: '会議地獄',
    description: '今週は会議が多すぎて開発時間が取れない。',
    severity: 'negative',
    flavor: '会議のための会議。これが社会だ。',
    choices: [
      {
        id: 'attend_all',
        label: '全て出席',
        description: '今週の全進捗が50%に減少。',
        effects: [{ type: 'progress_delta', value: -15 }],
      },
      {
        id: 'skip_some',
        label: '一部欠席',
        description: 'コスト増だが進捗への影響が少ない。',
        effects: [{ type: 'cost_delta', value: 30 }, { type: 'progress_delta', value: -5 }],
      },
    ],
  },
  {
    id: 'e_overtime',
    type: 'event',
    name: '残業スパート',
    description: 'チームが自発的に残業を申し出た。進捗は上がるがコンディションに影響。',
    severity: 'neutral',
    flavor: '「頑張ります」の後が心配だ。',
    choices: [
      {
        id: 'allow',
        label: '認める',
        description: '今週の進捗+30%。次のターンのコンディションが下がる。',
        effects: [{ type: 'progress_delta', value: 20 }, { type: 'cost_delta', value: 50 }],
      },
      {
        id: 'deny',
        label: '帰らせる',
        description: '進捗への変化なし。チームのコンディション維持。',
        effects: [],
      },
    ],
  },
  {
    id: 'e_new_tool',
    type: 'event',
    name: '新ツール導入提案',
    description: '「このツール使えば生産性が上がります」。エンジニアが新ツールを提案。',
    severity: 'neutral',
    flavor: 'バズワードが含まれていたら要注意。',
    choices: [
      {
        id: 'adopt',
        label: '導入する',
        description: '学習コスト1ターン。その後は生産性+10%。',
        effects: [{ type: 'progress_delta', value: -15 }, { type: 'quality_delta', value: 5 }],
      },
      {
        id: 'reject',
        label: '見送る',
        description: '変化なし。',
        effects: [],
      },
    ],
  },
]
