import type { MissionDef } from '../types/mission'

export const MISSION_POOL: MissionDef[] = [
  {
    id: 'complete_game',
    name: 'プロジェクト完遂',
    description: 'プロジェクトをクリアせよ',
    reward: 40,
    conditionType: 'complete_game',
    displayTarget: 'クリア',
  },
  {
    id: 'quality_guardian',
    name: '品質番人',
    description: 'クリア時に品質70以上を維持する',
    reward: 40,
    conditionType: 'quality_above_on_win',
    conditionValue: 70,
    displayTarget: '品質70+',
  },
  {
    id: 'high_quality',
    name: '品質王',
    description: 'クリア時に品質85以上を達成する',
    reward: 60,
    conditionType: 'quality_above_on_win',
    conditionValue: 85,
    displayTarget: '品質85+',
  },
  {
    id: 'speed_runner',
    name: 'スピードランナー',
    description: '規定ターン数の75%以内でクリアする',
    reward: 80,
    conditionType: 'finish_within_turn_percent',
    conditionValue: 75,
    displayTarget: '75%以内',
  },
  {
    id: 'budget_master',
    name: '予算マスター',
    description: '予算の60%以内でクリアする',
    reward: 70,
    conditionType: 'budget_under_percent',
    conditionValue: 60,
    displayTarget: '予算60%以内',
  },
  {
    id: 'bug_free',
    name: 'バグゼロ伝説',
    description: 'クリア時の総バグ数を3個以下にする',
    reward: 80,
    conditionType: 'max_bugs_on_win',
    conditionValue: 3,
    displayTarget: 'バグ3個以下',
  },
  {
    id: 'productive_week',
    name: '神がかった週',
    description: '1ターンで2つ以上のタスクを完了する',
    reward: 50,
    conditionType: 'tasks_in_one_turn',
    conditionValue: 2,
    displayTarget: '1T2タスク完了',
  },
  {
    id: 'full_team',
    name: 'フルチーム稼働',
    description: '3人以上を同時に稼働させる',
    reward: 40,
    conditionType: 'simultaneous_personnel',
    conditionValue: 3,
    displayTarget: '3人同時稼働',
  },
  {
    id: 'budget_saver',
    name: '予算の錬金術師',
    description: '予算の80%以内でクリアする',
    reward: 40,
    conditionType: 'budget_under_percent',
    conditionValue: 80,
    displayTarget: '予算80%以内',
  },
]
