import type { SkillDef } from '../types/skill'

export const SKILL_TREE: SkillDef[] = [
  // ── Tier 1: 基礎スキル ─────────────────────────────────
  {
    id: 'task_management',
    name: 'タスク管理術',
    description: '手札上限が+1増える。より多くの選択肢を保持できる。',
    cost: 50,
    tier: 1,
    category: 'management',
    requires: [],
    effect: { handSizeBonus: 1 },
  },
  {
    id: 'code_review',
    name: 'コードレビュー',
    description: 'バグ発生率が20%減少する。品質が安定する。',
    cost: 50,
    tier: 1,
    category: 'tech',
    requires: [],
    effect: { bugRateMultiplier: 0.8 },
  },
  {
    id: 'risk_identification',
    name: 'リスク洗出し',
    description: 'ランダムイベントの発生確率が10%低下する。',
    cost: 50,
    tier: 1,
    category: 'risk',
    requires: [],
    effect: { eventProbReduction: 0.1 },
  },
  {
    id: 'one_on_one',
    name: '1on1面談',
    description: '週次コンディション回復量が+3。メンバーの疲弊を防ぐ。',
    cost: 50,
    tier: 1,
    category: 'leadership',
    requires: [],
    effect: { conditionRecoveryBonus: 3 },
  },

  // ── Tier 2: 中級スキル ─────────────────────────────────
  {
    id: 'resource_optimization',
    name: 'リソース最適化',
    description: '人員コストが10%削減される。予算効率が向上する。',
    cost: 100,
    tier: 2,
    category: 'management',
    requires: ['task_management'],
    effect: { personnelCostMultiplier: 0.9 },
  },
  {
    id: 'cicd',
    name: 'CI/CD導入',
    description: '全人員の生産性が+5pt/週。自動化の恩恵を受ける。',
    cost: 100,
    tier: 2,
    category: 'tech',
    requires: ['code_review'],
    effect: { productivityBonus: 5 },
  },
  {
    id: 'contingency',
    name: 'コンティンジェンシー',
    description: '予算超過ゲームオーバーラインが+10%拡張される。',
    cost: 100,
    tier: 2,
    category: 'risk',
    requires: ['risk_identification'],
    effect: { budgetBufferBonus: 0.1 },
  },
  {
    id: 'team_building',
    name: 'チームビルディング',
    description: '継続作業ボーナスが10%UP。チームの連携力が向上する。',
    cost: 100,
    tier: 2,
    category: 'leadership',
    requires: ['one_on_one'],
    effect: { continuityBonusMultiplier: 1.1 },
  },

  // ── Tier 3: 上級スキル ─────────────────────────────────
  {
    id: 'pmp',
    name: 'PMP資格取得',
    description: '手札+1、生産性+3、人員コスト-5%の複合効果を得る。',
    cost: 200,
    tier: 3,
    category: 'management',
    requires: ['resource_optimization', 'cicd'],
    effect: { handSizeBonus: 1, productivityBonus: 3, personnelCostMultiplier: 0.95 },
  },
  {
    id: 'vision',
    name: 'ビジョン策定',
    description: 'プロジェクト開始時の品質が+10からスタートする。',
    cost: 150,
    tier: 3,
    category: 'leadership',
    requires: ['team_building'],
    effect: { startQualityBonus: 10 },
  },
  {
    id: 'crisis_management',
    name: '危機管理計画',
    description: '品質ゲームオーバーラインが-10下がる。崩壊に強くなる。',
    cost: 150,
    tier: 3,
    category: 'risk',
    requires: ['contingency'],
    effect: { qualityMinReduction: 10 },
  },
]
