import type { SkillDef } from '../types/skill'

export const SKILL_TREE: SkillDef[] = [
  // ── Tier 1: 基礎スキル ─────────────────────────────────
  {
    id: 'task_management',
    name: 'タスク分解の達人',
    description: '「これ、もっと細かく切れる」手札上限が+1。常に2手先の択を持ち、詰みを防ぐ。',
    cost: 30,
    tier: 1,
    category: 'management',
    requires: [],
    effect: { handSizeBonus: 1 },
  },
  {
    id: 'code_review',
    name: 'レビュー道場',
    description: '「このif文、誰の意図？」レビューが文化になればバグは激減。バグ発生率が40%削減される。',
    cost: 30,
    tier: 1,
    category: 'tech',
    requires: [],
    effect: { bugRateMultiplier: 0.6 },
  },
  {
    id: 'risk_identification',
    name: '嫌な予感センサー',
    description: '「なんか嫌な予感がする…」PM歴から培われた第六感。ランダムイベント発生率が20%低下する。',
    cost: 30,
    tier: 1,
    category: 'risk',
    requires: [],
    effect: { eventProbReduction: 0.2 },
  },
  {
    id: 'one_on_one',
    name: '1on1マスター',
    description: '「最近どう？」この一言が刺さる。週次コンディション回復量が大幅強化、チームが疲弊しにくくなる。',
    cost: 30,
    tier: 1,
    category: 'leadership',
    requires: [],
    effect: { conditionRecoveryBonus: 8 },
  },

  // ── Tier 2: 中級スキル ─────────────────────────────────
  {
    id: 'resource_optimization',
    name: '人員パズルの鬼',
    description: '「この人、ここじゃなくてあっちでしょ」絶妙な配置で人員コストが20%削減。予算の余裕が戦略の幅になる。',
    cost: 80,
    tier: 2,
    category: 'management',
    requires: ['task_management'],
    effect: { personnelCostMultiplier: 0.8 },
  },
  {
    id: 'cicd',
    name: '自動化の伝道師',
    description: '「手作業？それ自動化できます」CI/CDが全員を底上げ。生産性+10は積み重なると圧倒的になる。',
    cost: 80,
    tier: 2,
    category: 'tech',
    requires: ['code_review'],
    effect: { productivityBonus: 10 },
  },
  {
    id: 'contingency',
    name: 'バッファ信仰の使徒',
    description: '「いやバッファ込みで積んでるんで」予算超過ゲームオーバーラインが20%拡張。崩壊寸前から立て直せる。',
    cost: 80,
    tier: 2,
    category: 'risk',
    requires: ['risk_identification'],
    effect: { budgetBufferBonus: 0.2 },
  },
  {
    id: 'team_building',
    name: 'チームの火付け役',
    description: '「このチームなら絶対やれる！」継続作業ボーナスが40%強化。同じメンバーで走り続けるほど爆発する。',
    cost: 80,
    tier: 2,
    category: 'leadership',
    requires: ['one_on_one'],
    effect: { continuityBonusMultiplier: 1.4 },
  },

  // ── Tier 3: 上級スキル ─────────────────────────────────
  {
    id: 'pmp',
    name: 'PMP取得済み（実力もある）',
    description: '資格だけじゃない、裏付けのある強さ。手札+1・生産性+8・人員コスト-10%の三重バフが全局面を底上げする。',
    cost: 160,
    tier: 3,
    category: 'management',
    requires: ['resource_optimization', 'cicd'],
    effect: { handSizeBonus: 1, productivityBonus: 8, personnelCostMultiplier: 0.9 },
  },
  {
    id: 'vision',
    name: 'ビジョンの描き手',
    description: '「目指すものが見えれば、人は動く」プロジェクト開始時の品質が+20。最初の景色の高さが勝負を決める。',
    cost: 120,
    tier: 3,
    category: 'leadership',
    requires: ['team_building'],
    effect: { startQualityBonus: 20 },
  },
  {
    id: 'crisis_management',
    name: '炎上サバイバー',
    description: 'あの修羅場があったから今がある。品質ゲームオーバーラインが15下がり、崖っぷちからでも這い上がれる。',
    cost: 120,
    tier: 3,
    category: 'risk',
    requires: ['contingency'],
    effect: { qualityMinReduction: 15 },
  },
]
